INSERT INTO categories (id, name, slug, icon, created_at, updated_at) VALUES
(1, 'Arcade', 'arcade', '🕹️', NOW(), NOW()),
(2, 'Trí tuệ', 'tri-tue', '🧠', NOW(), NOW()),
(3, 'Hành động', 'hanh-dong', '⚔️', NOW(), NOW()),
(4, 'Thể thao', 'the-thao', '⚽', NOW(), NOW()),
(5, 'Đua xe', 'dua-xe', '🏎️', NOW(), NOW()),
(6, 'Bắn súng', 'ban-sung', '🔫', NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name);

INSERT INTO games (id, title, slug, thumbnail, play_url, description, controls_guide, play_count, rating_avg, badge, status, created_at, updated_at) VALUES
(1, '2048 Classic Puzzle', '2048-classic', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80', '/games/2048/index.html', 'Trò chơi giải đố ghép số 2048 kinh điển do hệ thống tự host.', 'Phím mũi tên (← ↑ → ↓) hoặc W, A, S, D', 124500, 4.90, 'HOT', 'published', NOW(), NOW()),
(2, 'Tetris Xếp Gạch Cổ Điển', 'tetris-classic', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80', '/games/tetris-classic/index.html', 'Tựa game xếp gạch Tetris huyền thoại.', 'Phím ← / → di chuyển, ↑ xoay khối, ↓ hạ nhanh, Space thả rơi ngay', 185000, 4.95, 'HOT', 'published', NOW(), NOW()),
(3, 'Flappy Bird Cyber Retro', 'flappy-bird-cyber', 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80', '/games/flappy-bird/index.html', 'Điều khiển chú chim Cyber bay luồn lách qua các đường ống.', 'Phím Space hoặc Click chuột để vỗ cánh bay', 142000, 4.85, 'NEW', 'published', NOW(), NOW()),
(4, 'Snake Retro 1997', 'snake-retro-1997', 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=600&auto=format&fit=crop&q=80', '/games/snake-retro/index.html', 'Tựa game Rắn săn mồi kinh điển phong cách máy gạch 1997.', 'W, A, S, D hoặc Phím mũi tên điều hướng rắn', 95400, 4.75, 'HOT', 'published', NOW(), NOW()),
(5, 'Brick Breaker Arkanoid', 'brick-breaker', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80', '/games/brick-breaker/index.html', 'Game bắn bóng phá gạch Arkanoid cổ điển.', 'Di chuyển chuột hoặc phím A, D để hứng bóng, Space để bắn', 84200, 4.80, 'NEW', 'published', NOW(), NOW()),
(6, 'Space Invaders 1978', 'space-invaders-1978', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80', '/games/space-invaders/index.html', 'Bảo vệ dải ngân hà chống lại hạm đội người ngoài hành tinh xâm lăng.', 'Phím A, D (← →) di chuyển phi thuyền, Phím Space bắn đạn laser', 112000, 4.88, 'HOT', 'published', NOW(), NOW()),
(7, 'Minesweeper Dò Mìn', 'minesweeper-classic', 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&auto=format&fit=crop&q=80', '/games/minesweeper/index.html', 'Game Dò mìn trí tuệ Windows kinh điển.', 'Chuột trái mở ô, Chuột phải (hoặc giữ lâu) cắm cờ 🚩', 67500, 4.70, 'NORMAL', 'published', NOW(), NOW()),
(8, 'Pong Retro 1972', 'pong-retro-1972', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80', '/games/pong-retro/index.html', 'Tựa game bóng bàn điện tử đầu tiên trong lịch sử loài người.', 'Chuột hoặc phím W, S (↑ ↓) để di chuyển thanh đỡ bóng', 54300, 4.65, 'NORMAL', 'published', NOW(), NOW()),
(9, 'Memory Match Lật Thẻ', 'memory-match', 'https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?w=600&auto=format&fit=crop&q=80', '/games/memory-match/index.html', 'Trò chơi rèn luyện trí nhớ lật các cặp hình emoji.', 'Click chuột để lật mở thẻ bài', 43800, 4.60, 'NORMAL', 'published', NOW(), NOW()),
(10, 'Tic Tac Toe Đấu Trí AI', 'tictactoe-ai', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80', '/games/tictactoe-ai/index.html', 'Cờ Ca-rô 3x3 cổ điển với thuật toán AI.', 'Click chuột vào ô để đánh dấu X hoặc O', 61200, 4.72, 'NORMAL', 'published', NOW(), NOW()),
(11, 'Pacman Canvas Classic', 'pacman-canvas', 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80', '/games/pacman-canvas/index.html', 'Pacman ăn hạt đậu trong mê cung.', 'Phím mũi tên (← ↑ → ↓) hoặc W, A, S, D', 195000, 4.98, 'HOT', 'published', NOW(), NOW()),
(12, 'Tower Building 3D', 'tower-building-3d', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80', '/games/tower-building/index.html', 'Xây dựng tòa tháp chọc trời cao nhất có thể.', 'Chuột trái hoặc Phím Space để thả tầng nhà', 76430, 4.70, 'WEBGL', 'published', NOW(), NOW()),
(13, 'Hextris Arcade 360°', 'hextris-arcade', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80', '/games/hextris/index.html', 'Game xếp hình lục giác tốc độ cao tự host.', 'Phím A, D hoặc Mũi tên Trái / Phải (← →)', 98210, 4.80, 'HOT', 'published', NOW(), NOW()),
(14, 'Copter Cave Trực Thăng', 'copter-cave', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80', '/games/flappy-helicopter/index.html', 'Lái trực thăng luồn lách qua các hang động hiểm trở.', 'Giữ chuột trái hoặc phím Space để bay lên, thả ra để hạ độ cao', 88900, 4.78, 'NEW', 'published', NOW(), NOW()),
(15, '3D Free Kick World Cup', '3d-free-kick', 'https://img.famobi.com/portal/html5games/images/tmp/3d-free-kick_teaser.jpg', 'https://play.famobi.com/3d-free-kick', 'Thử tài sút phạt đền bóng đá 3D.', 'Vuốt chuột hoặc ngón tay để tạo đường cong và lực sút bóng', 245000, 4.92, 'HOT', 'published', NOW(), NOW()),
(16, '8 Ball Billiards Classic', '8-ball-billiards-classic', 'https://img.famobi.com/portal/html5games/images/tmp/8-ball-billiards-classic_teaser.jpg', 'https://play.famobi.com/8-ball-billiards-classic', 'Trò chơi Bi-a 8 bóng kinh điển.', 'Kéo chuột để chỉnh hướng cơ và kéo thanh lực để đánh bi', 312000, 4.96, 'HOT', 'published', NOW(), NOW()),
(17, 'Archery World Tour', 'archery-world-tour', 'https://img.famobi.com/portal/html5games/images/tmp/archery-world-tour_teaser.jpg', 'https://play.famobi.com/archery-world-tour', 'Trở thành cung thủ cừ khôi đi khắp thế giới.', 'Giữ và rê chuột để ngắm bắn, thả ra để bắn tên', 178000, 4.88, 'WEBGL', 'published', NOW(), NOW()),
(18, 'Bubble Tower 3D', 'bubble-tower-3d', 'https://img.famobi.com/portal/html5games/images/tmp/bubble-tower-3d_teaser.jpg', 'https://play.famobi.com/bubble-tower-3d', 'Bắn bóng tròn quanh tháp 3D xoay 360 độ.', 'Xoay tháp bằng chuột, nhấp để bắn bóng vào vị trí mong muốn', 198000, 4.85, 'WEBGL', 'published', NOW(), NOW()),
(19, 'Cannon Balls 3D', 'cannon-balls-3d', 'https://img.famobi.com/portal/html5games/images/tmp/cannon-balls-3d_teaser.jpg', 'https://play.famobi.com/cannon-balls-3d', 'Bắn đại bác phá hủy các công trình kiến trúc.', 'Nhấp chuột vào vị trí cần bắn đại bác', 165000, 4.82, 'NEW', 'published', NOW(), NOW()),
(20, 'Element Blocks 1010', 'element-blocks', 'https://img.famobi.com/portal/html5games/images/tmp/element-blocks_teaser.jpg', 'https://play.famobi.com/element-blocks', 'Trò chơi xếp khối gỗ nguyên tố.', 'Kéo thả các khối hình vào bàn cờ', 210000, 4.89, 'HOT', 'published', NOW(), NOW()),
(21, 'Moto X3M Pool Party', 'moto-x3m-pool-party', 'https://img.famobi.com/portal/html5games/images/tmp/moto-x3m-pool-party_teaser.jpg', 'https://play.famobi.com/moto-x3m-pool-party', 'Lái mô tô địa hình nhào lộn qua các công viên nước.', 'Phím ↑ để tăng ga, ↓ phanh, ← → để giữ thăng bằng', 389000, 4.98, 'HOT', 'published', NOW(), NOW()),
(22, 'Om Nom Run 3D', 'om-nom-run', 'https://img.famobi.com/portal/html5games/images/tmp/om-nom-run_teaser.jpg', 'https://play.famobi.com/om-nom-run', 'Đồng hành cùng chú ếch xanh Om Nom chạy vô tận.', 'Phím mũi tên ← → chuyển làn, ↑ nhảy, ↓ trượt', 420000, 4.97, 'HOT', 'published', NOW(), NOW()),
(23, 'Solitaire Klondike Classic', 'solitaire-klondike', 'https://img.famobi.com/portal/html5games/images/tmp/solitaire-klondike_teaser.jpg', 'https://play.famobi.com/solitaire-klondike', 'Game xếp bài Solitaire Klondike chuẩn mực.', 'Kéo thả hoặc nhấp đúp vào quân bài để di chuyển', 156000, 4.80, 'NORMAL', 'published', NOW(), NOW()),
(24, 'Table Tennis World Tour', 'table-tennis-world-tour', 'https://img.famobi.com/portal/html5games/images/tmp/table-tennis-world-tour_teaser.jpg', 'https://play.famobi.com/table-tennis-world-tour', 'Đại chiến bóng bàn đỉnh cao thế giới 3D.', 'Rê chuột để điều khiển vợt và cắt bóng', 205000, 4.91, 'HOT', 'published', NOW(), NOW()),
(25, 'Totemia Cursed Marbles', 'totemia-cursed-marbles', 'https://img.famobi.com/portal/html5games/images/tmp/totemia-cursed-marbles_teaser.jpg', 'https://play.famobi.com/totemia-cursed-marbles', 'Bắn bóng Zuma cổ tích Totemia.', 'Rê chuột ngắm và nhấp bắn bóng', 267000, 4.93, 'HOT', 'published', NOW(), NOW()),
(26, 'Tower Crash 3D Ball', 'tower-crash-3d', 'https://img.famobi.com/portal/html5games/images/tmp/tower-crash-3d_teaser.jpg', 'https://play.famobi.com/tower-crash-3d', 'Bắn các khối màu vào tòa tháp xoay 3D.', 'Xoay tháp bằng chuột và nhấp để bắn phá', 189000, 4.87, 'WEBGL', 'published', NOW(), NOW())
ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), thumbnail=VALUES(thumbnail);

INSERT IGNORE INTO game_category (game_id, category_id) VALUES 
(1, 1), (1, 2), (2, 1), (2, 2), (3, 1), (3, 3), (4, 1), (4, 2), (5, 1), (5, 3), (6, 1), (6, 6), (7, 2), (8, 1), (8, 4), (9, 2), (10, 2), (11, 1), (12, 1), (12, 3), (13, 1), (13, 2), (14, 1), (14, 3), (15, 4), (16, 4), (17, 4), (17, 6), (18, 1), (18, 2), (19, 2), (19, 3), (20, 1), (20, 2), (21, 3), (21, 5), (22, 1), (22, 3), (23, 2), (24, 4), (25, 1), (25, 2), (26, 2), (26, 3);
