<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Game;
use App\Models\Category;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gamesData = [
            // --- 14 GAME CỔ ĐIỂN TỰ HOST ---
            [
                'title' => '2048 Classic Puzzle',
                'slug' => '2048-classic',
                'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/2048/index.html',
                'description' => 'Trò chơi giải đố ghép số 2048 kinh điển do hệ thống tự host. Sử dụng các phím mũi tên hoặc vuốt màn hình để kết hợp các ô số giống nhau đạt mốc 2048!',
                'controls_guide' => 'Phím mũi tên (← ↑ → ↓) hoặc W, A, S, D',
                'play_count' => 124500,
                'rating_avg' => 4.90,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['tri-tue', 'arcade'],
            ],
            [
                'title' => 'Tetris Xếp Gạch Cổ Điển',
                'slug' => 'tetris-classic',
                'thumbnail' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/tetris-classic/index.html',
                'description' => 'Tựa game xếp gạch Tetris huyền thoại với đầy đủ các khối I, J, L, O, S, T, Z, tính điểm ăn hàng và tăng tốc độ theo cấp độ.',
                'controls_guide' => 'Phím ← / → di chuyển, ↑ xoay khối, ↓ hạ nhanh, Space thả rơi ngay',
                'play_count' => 185000,
                'rating_avg' => 4.95,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['arcade', 'tri-tue'],
            ],
            [
                'title' => 'Flappy Bird Cyber Retro',
                'slug' => 'flappy-bird-cyber',
                'thumbnail' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/flappy-bird/index.html',
                'description' => 'Điều khiển chú chim Cyber bay luồn lách qua các đường ống chướng ngại vật để ghi điểm kỷ lục.',
                'controls_guide' => 'Phím Space hoặc Click chuột để vỗ cánh bay',
                'play_count' => 142000,
                'rating_avg' => 4.85,
                'badge' => 'NEW',
                'status' => 'published',
                'category_slugs' => ['arcade', 'hanh-dong'],
            ],
            [
                'title' => 'Snake Retro 1997',
                'slug' => 'snake-retro-1997',
                'thumbnail' => 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/snake-retro/index.html',
                'description' => 'Tựa game Rắn săn mồi kinh điển phong cách máy gạch 1997 với bảng điểm và hiệu ứng mượt mà.',
                'controls_guide' => 'W, A, S, D hoặc Phím mũi tên điều hướng rắn',
                'play_count' => 95400,
                'rating_avg' => 4.75,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['arcade', 'tri-tue'],
            ],
            [
                'title' => 'Brick Breaker Arkanoid',
                'slug' => 'brick-breaker',
                'thumbnail' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/brick-breaker/index.html',
                'description' => 'Game bắn bóng phá gạch Arkanoid cổ điển với thanh trượt mượt mà, nhiều tầng gạch màu sắc và điểm combo.',
                'controls_guide' => 'Di chuyển chuột hoặc phím A, D để hứng bóng, Space để bắn',
                'play_count' => 84200,
                'rating_avg' => 4.80,
                'badge' => 'NEW',
                'status' => 'published',
                'category_slugs' => ['arcade', 'hanh-dong'],
            ],
            [
                'title' => 'Space Invaders 1978',
                'slug' => 'space-invaders-1978',
                'thumbnail' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/space-invaders/index.html',
                'description' => 'Bảo vệ dải ngân hà chống lại hạm đội người ngoài hành tinh xâm lăng trong không gian vũ trụ.',
                'controls_guide' => 'Phím A, D (← →) di chuyển phi thuyền, Phím Space bắn đạn laser',
                'play_count' => 112000,
                'rating_avg' => 4.88,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['ban-sung', 'arcade'],
            ],
            [
                'title' => 'Minesweeper Dò Mìn',
                'slug' => 'minesweeper-classic',
                'thumbnail' => 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/minesweeper/index.html',
                'description' => 'Game Dò mìn trí tuệ Windows kinh điển với cơ chế cắm cờ, tính thời gian và tự động mở vùng trống an toàn.',
                'controls_guide' => 'Chuột trái mở ô, Chuột phải (hoặc giữ lâu) cắm cờ 🚩',
                'play_count' => 67500,
                'rating_avg' => 4.70,
                'badge' => 'NORMAL',
                'status' => 'published',
                'category_slugs' => ['tri-tue'],
            ],
            [
                'title' => 'Pong Retro 1972',
                'slug' => 'pong-retro-1972',
                'thumbnail' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/pong-retro/index.html',
                'description' => 'Tựa game bóng bàn điện tử đầu tiên trong lịch sử loài người, hỗ trợ chế độ đối kháng với AI thông minh.',
                'controls_guide' => 'Chuột hoặc phím W, S (↑ ↓) để di chuyển thanh đỡ bóng',
                'play_count' => 54300,
                'rating_avg' => 4.65,
                'badge' => 'NORMAL',
                'status' => 'published',
                'category_slugs' => ['the-thao', 'arcade'],
            ],
            [
                'title' => 'Memory Match Lật Thẻ',
                'slug' => 'memory-match',
                'thumbnail' => 'https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/memory-match/index.html',
                'description' => 'Trò chơi rèn luyện trí nhớ lật các cặp hình emoji giống nhau trong thời gian ngắn nhất.',
                'controls_guide' => 'Click chuột để lật mở thẻ bài',
                'play_count' => 43800,
                'rating_avg' => 4.60,
                'badge' => 'NORMAL',
                'status' => 'published',
                'category_slugs' => ['tri-tue'],
            ],
            [
                'title' => 'Tic Tac Toe Đấu Trí AI',
                'slug' => 'tictactoe-ai',
                'thumbnail' => 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/tictactoe-ai/index.html',
                'description' => 'Cờ Ca-rô 3x3 cổ điển với thuật toán AI tìm nước đi tối ưu hoặc chế độ 2 người chơi cùng máy.',
                'controls_guide' => 'Click chuột vào ô để đánh dấu X hoặc O',
                'play_count' => 61200,
                'rating_avg' => 4.72,
                'badge' => 'NORMAL',
                'status' => 'published',
                'category_slugs' => ['tri-tue'],
            ],
            [
                'title' => 'Pacman Canvas Classic',
                'slug' => 'pacman-canvas',
                'thumbnail' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/pacman-canvas/index.html',
                'description' => 'Pacman ăn hạt đậu trong mê cung tránh bóng ma Blinky màu đỏ, mượt mà chạy bằng HTML5 Canvas.',
                'controls_guide' => 'Phím mũi tên (← ↑ → ↓) hoặc W, A, S, D',
                'play_count' => 195000,
                'rating_avg' => 4.98,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['arcade'],
            ],
            [
                'title' => 'Tower Building 3D',
                'slug' => 'tower-building-3d',
                'thumbnail' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/tower-building/index.html',
                'description' => 'Xây dựng tòa tháp chọc trời cao nhất có thể bằng cách căn thời gian thả từng tầng lầu chuẩn xác.',
                'controls_guide' => 'Chuột trái hoặc Phím Space để thả tầng nhà',
                'play_count' => 76430,
                'rating_avg' => 4.70,
                'badge' => 'WEBGL',
                'status' => 'published',
                'category_slugs' => ['hanh-dong', 'arcade'],
            ],
            [
                'title' => 'Hextris Arcade 360°',
                'slug' => 'hextris-arcade',
                'thumbnail' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/hextris/index.html',
                'description' => 'Game xếp hình lục giác tốc độ cao tự host. Xoay khối lục giác để ghép 3 khối cùng màu trước khi chạm đỉnh!',
                'controls_guide' => 'Phím A, D hoặc Mũi tên Trái / Phải (← →)',
                'play_count' => 98210,
                'rating_avg' => 4.80,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['arcade', 'tri-tue'],
            ],
            [
                'title' => 'Copter Cave Trực Thăng',
                'slug' => 'copter-cave',
                'thumbnail' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
                'play_url' => 'http://127.0.0.1:8000/games/flappy-helicopter/index.html',
                'description' => 'Lái trực thăng luồn lách qua các hang động hiểm trở và chướng ngại vật ngẫu nhiên.',
                'controls_guide' => 'Giữ chuột trái hoặc phím Space để bay lên, thả ra để hạ độ cao',
                'play_count' => 88900,
                'rating_avg' => 4.78,
                'badge' => 'NEW',
                'status' => 'published',
                'category_slugs' => ['hanh-dong', 'arcade'],
            ],

            // --- 12 GAME MỚI TỪ FAMOBI (URL NHÚNG HTML5 CAO CẤP) ---
            [
                'title' => '3D Free Kick World Cup',
                'slug' => '3d-free-kick',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/3d-free-kick_teaser.jpg',
                'play_url' => 'https://play.famobi.com/3d-free-kick',
                'description' => 'Thử tài sút phạt đền bóng đá 3D vượt qua hàng rào phòng ngự và đánh bại thủ môn siêu đẳng để đưa đội tuyển vô địch thế giới.',
                'controls_guide' => 'Vuốt chuột hoặc ngón tay để tạo đường cong và lực sút bóng',
                'play_count' => 245000,
                'rating_avg' => 4.92,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['the-thao'],
            ],
            [
                'title' => '8 Ball Billiards Classic',
                'slug' => '8-ball-billiards-classic',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/8-ball-billiards-classic_teaser.jpg',
                'play_url' => 'https://play.famobi.com/8-ball-billiards-classic',
                'description' => 'Trò chơi Bi-a 8 bóng kinh điển với vật lý chân thực, hỗ trợ ngắm đường bóng chính xác và thi đấu đối kháng.',
                'controls_guide' => 'Kéo chuột để chỉnh hướng cơ và kéo thanh lực để đánh bi',
                'play_count' => 312000,
                'rating_avg' => 4.96,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['the-thao'],
            ],
            [
                'title' => 'Archery World Tour',
                'slug' => 'archery-world-tour',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/archery-world-tour_teaser.jpg',
                'play_url' => 'https://play.famobi.com/archery-world-tour',
                'description' => 'Trở thành cung thủ cừ khôi đi khắp thế giới, căn chỉnh sức gió và độ rung để bắn trúng hồng tâm 10 điểm.',
                'controls_guide' => 'Giữ và rê chuột để ngắm bắn, thả ra để bắn tên',
                'play_count' => 178000,
                'rating_avg' => 4.88,
                'badge' => 'WEBGL',
                'status' => 'published',
                'category_slugs' => ['the-thao', 'ban-sung'],
            ],
            [
                'title' => 'Bubble Tower 3D',
                'slug' => 'bubble-tower-3d',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/bubble-tower-3d_teaser.jpg',
                'play_url' => 'https://play.famobi.com/bubble-tower-3d',
                'description' => 'Bắn bóng tròn quanh tháp 3D xoay 360 độ, kết hợp từ 3 quả bóng cùng màu để phá hủy tòa tháp bong bóng.',
                'controls_guide' => 'Xoay tháp bằng chuột, nhấp để bắn bóng vào vị trí mong muốn',
                'play_count' => 198000,
                'rating_avg' => 4.85,
                'badge' => 'WEBGL',
                'status' => 'published',
                'category_slugs' => ['tri-tue', 'arcade'],
            ],
            [
                'title' => 'Cannon Balls 3D',
                'slug' => 'cannon-balls-3d',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/cannon-balls-3d_teaser.jpg',
                'play_url' => 'https://play.famobi.com/cannon-balls-3d',
                'description' => 'Bắn đại bác phá hủy các công trình kiến trúc hình học 3D phức tạp với hiệu ứng vật lý sụp đổ mãn nhãn.',
                'controls_guide' => 'Nhấp chuột vào vị trí cần bắn đại bác',
                'play_count' => 165000,
                'rating_avg' => 4.82,
                'badge' => 'NEW',
                'status' => 'published',
                'category_slugs' => ['hanh-dong', 'tri-tue'],
            ],
            [
                'title' => 'Element Blocks 1010',
                'slug' => 'element-blocks',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/element-blocks_teaser.jpg',
                'play_url' => 'https://play.famobi.com/element-blocks',
                'description' => 'Trò chơi xếp khối gỗ nguyên tố phong cách 1010 giải đố cực kỳ lôi cuốn, xếp kín hàng ngang hoặc dọc để ghi điểm.',
                'controls_guide' => 'Kéo thả các khối hình vào bàn cờ',
                'play_count' => 210000,
                'rating_avg' => 4.89,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['tri-tue', 'arcade'],
            ],
            [
                'title' => 'Moto X3M Pool Party',
                'slug' => 'moto-x3m-pool-party',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/moto-x3m-pool-party_teaser.jpg',
                'play_url' => 'https://play.famobi.com/moto-x3m-pool-party',
                'description' => 'Lái mô tô địa hình nhào lộn qua các công viên nước, vượt qua bẫy chông, vòng xoáy nước và thực hiện pha lộn nhào 360 độ.',
                'controls_guide' => 'Phím ↑ để tăng ga, ↓ phanh, ← → để giữ thăng bằng',
                'play_count' => 389000,
                'rating_avg' => 4.98,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['dua-xe', 'hanh-dong'],
            ],
            [
                'title' => 'Om Nom Run 3D',
                'slug' => 'om-nom-run',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/om-nom-run_teaser.jpg',
                'play_url' => 'https://play.famobi.com/om-nom-run',
                'description' => 'Đồng hành cùng chú ếch xanh Om Nom chạy vô tận qua đường phố Nomville, né xe cộ, nhảy dù và thu thập tiền vàng.',
                'controls_guide' => 'Phím mũi tên ← → chuyển làn, ↑ nhảy, ↓ trượt',
                'play_count' => 420000,
                'rating_avg' => 4.97,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['hanh-dong', 'arcade'],
            ],
            [
                'title' => 'Solitaire Klondike Classic',
                'slug' => 'solitaire-klondike',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/solitaire-klondike_teaser.jpg',
                'play_url' => 'https://play.famobi.com/solitaire-klondike',
                'description' => 'Game xếp bài Solitaire Klondike chuẩn mực huyền thoại, sắp xếp các quân bài từ Át đến K theo chất.',
                'controls_guide' => 'Kéo thả hoặc nhấp đúp vào quân bài để di chuyển',
                'play_count' => 156000,
                'rating_avg' => 4.80,
                'badge' => 'NORMAL',
                'status' => 'published',
                'category_slugs' => ['tri-tue'],
            ],
            [
                'title' => 'Table Tennis World Tour',
                'slug' => 'table-tennis-world-tour',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/table-tennis-world-tour_teaser.jpg',
                'play_url' => 'https://play.famobi.com/table-tennis-world-tour',
                'description' => 'Đại chiến bóng bàn đỉnh cao thế giới 3D, thi đấu với các tuyển thủ quốc tế và tung ra những cú vụt bóng xoáy uy lực.',
                'controls_guide' => 'Rê chuột để điều khiển vợt và cắt bóng',
                'play_count' => 205000,
                'rating_avg' => 4.91,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['the-thao'],
            ],
            [
                'title' => 'Totemia Cursed Marbles',
                'slug' => 'totemia-cursed-marbles',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/totemia-cursed-marbles_teaser.jpg',
                'play_url' => 'https://play.famobi.com/totemia-cursed-marbles',
                'description' => 'Bắn bóng Zuma cổ tích Totemia, bắn các viên bi cùng màu vào chuỗi hạt đang trượt để ngăn chúng rơi vào miệng hố thần thoại.',
                'controls_guide' => 'Rê chuột ngắm và nhấp bắn bóng',
                'play_count' => 267000,
                'rating_avg' => 4.93,
                'badge' => 'HOT',
                'status' => 'published',
                'category_slugs' => ['tri-tue', 'arcade'],
            ],
            [
                'title' => 'Tower Crash 3D Ball',
                'slug' => 'tower-crash-3d',
                'thumbnail' => 'https://img.famobi.com/portal/html5games/images/tmp/tower-crash-3d_teaser.jpg',
                'play_url' => 'https://play.famobi.com/tower-crash-3d',
                'description' => 'Bắn các khối màu vào tòa tháp xoay 3D để tạo phản ứng dây chuyền làm sụp đổ toàn bộ tòa tháp.',
                'controls_guide' => 'Xoay tháp bằng chuột và nhấp để bắn phá',
                'play_count' => 189000,
                'rating_avg' => 4.87,
                'badge' => 'WEBGL',
                'status' => 'published',
                'category_slugs' => ['tri-tue', 'hanh-dong'],
            ],
        ];

        foreach ($gamesData as $data) {
            $catSlugs = $data['category_slugs'];
            unset($data['category_slugs']);

            $game = Game::updateOrCreate(['slug' => $data['slug']], $data);

            $categoryIds = Category::whereIn('slug', $catSlugs)->pluck('id');
            $game->categories()->sync($categoryIds);
        }
    }
}
